services:
- type: web
name: telegram-image-compress-bot
env: python
buildCommand: "pip install -r requirements.txt"
startCommand: "python bot.py"
autoDeploy: true
envVars:
- key: TOKEN
sync: false